package com.ncinga.aaa.util;

public enum ResponseCode {
    ADD_AVP_RECORD_SUCCESS,
    ADD_AVP_RECORD_FAILED,
    GET_ALL_AVP_RECORD_SUCCESS,
    GET_ALL_AVP_RECORD_FAILED,
    UPDATE_AVP_RECORD_SUCCESS,
    UPDATE_AVP_RECORD_FAILED,
   DELETE_AVP_RECORD_SUCCESS,
    DELETE_AVP_RECORD_FAILED,
    SEARCH_SUCCESS,
    SEARCH_FAILED,
   GET_AVP_RECORD_SUCCESS,
    GET_AVP_RECORD_FAILED,
    ADD_ACCOUNT_SUCCESS,
    ADD_ACCOUNT_FAILED,
    GET_ACCOUNTS_SUCCESS,
    GET_ACCOUNTS_FAILED,
    EDIT_ACCOUNTS_SUCCESS,
    EDIT_ACCOUNTS_FAILED,
    GET_ACCOUNT_SUCCESS,
    GET_ACCOUNT_FAILED,
    DELETE_ACCOUNTS_SUCCESS,
    DELETE_ACCOUNTS_FAILED

}
