package com.ncinga.aaa.util;

public enum ResponseCode {
    ADD_AVP_RECORD_SUCCESS,
    ADD_AVP_RECORD_FAILED,
    GET_ALL_AVP_RECORD_SUCCESS,
    GET_ALL_AVP_RECORD_FAILED,
    UPDATE_AVP_RECORD_SUCCESS,
    UPDATE_AVP_RECORD_FAILED,
   DELETE_AVP_RECORD_SUCCESS,
    DELETE_AVP_RECORD_FAILED,
    SEARCH_SUCCESS,
    SEARCH_FAILED,

}
